# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-17 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='block',
            fields=[
                ('block_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Type', models.CharField(max_length=15, null=True)),
                ('ID', models.CharField(max_length=30, null=True)),
                ('descendants', models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
